### ISSUE TITLE
Remember previous selection

### ISSUE THREAD

**Issue by tylerjpines** [fedecalendino/alfred-emoji-mate#11]
Thanks for doing this project, the old ones are definitely dated :). Quick feature request: would be super helpful to remember previous emoji selections and start ranking them higher. Could see this in two ways, ideally both:

1) on keyword, show recents
2) on search, rank recents higher

Also, any ways to add our own keywords to emojis?

**Comment by fedecalendino** [comment]
Hi! Sorry for the late response, I'll give this a think. Having a "recently used" / "most used" options would be great!

Thank you for the suggestion, I'll add it to my Trello :)


Cheers, Fede!
