### ISSUE TITLE
[feature] emoji to text

### ISSUE THREAD

**Issue by Hansanghyeon** [fedecalendino/alfred-emoji-mate#17]
Hi fedecalendino,
The alfred-emoji-mate workflow is really awesome.

However, there are times when I want to find an emoji by text and times when I'm curious about what text an emoji represents. It would be great if you could add a feature to find text by inputting an emoji as well.

If you have time, please consider it.

Thanks a lot.

_translate chatGPT_

**Comment by fedecalendino** [comment]
Hi @Hansanghyeon !

This was a great idea, I added it in the latest version (`v2.2.0`). 

You can find it here:
https://github.com/fedecalendino/alfred-emoji-mate/releases/tag/v2.2.0

<img width="828" alt="search by emoji" src="https://github.com/user-attachments/assets/54117159-363f-4867-b22d-0272e2f5154c">


Cheers, Fede.
