### ISSUE TITLE
FEATURE: Add "yellow" skintone

### ISSUE THREAD

**Issue by gabrielwhite** [fedecalendino/alfred-emoji-mate#5]
I've just started using Emoji Mate and it's great. But I prefer to be yellow than a shade of pink/brown. Could you add "yellow" to the skin tone selection list?

**Comment by fedecalendino** [comment]
Hi! I'll give it a try!

Fede.

**Comment by fedecalendino** [comment]
@gabrielwhite I added it on v1.9.0.

Feel free to check it out and tell me if that is what you need!


Cheers, Fede.

**Comment by gabrielwhite** [comment]
🙌️

**Comment by gabrielwhite** [comment]
Thank you!
