### ISSUE TITLE
Search doesn’t seem to be working consistently

### ISSUE THREAD

**Issue by nourmalaeb** [fedecalendino/alfred-emoji-mate#6]
If I search for `zap` or `lightning` I don’t get the ⚡️ emoji. Search is generally slow and inconsistent.

**Comment by fedecalendino** [comment]
Hi! I'll give it a look.

Seems that someone posted my workflows into Alfred Gallery and now I'm getting a decent amount of requests.

Thanks for letting me know.

Fede

**Comment by nourmalaeb** [comment]
Yes that’s where I found it. I love it! Thank you.

**Comment by fedecalendino** [comment]
@nourmalaeb I think I fixed it on the version v1.9.1.

I'll try to speed up the search when I have more time.

Please, feel free to check it out and tell me if its a bit better.

Cheers,
Fede.

**Comment by nourmalaeb** [comment]
Thanks @fedecalendino — how do I update to v1.9.1? Do I need to build from source?

**Comment by fedecalendino** [comment]
You need to download and install the alfred file within the releases section in this repo. on the right.

**Comment by nourmalaeb** [comment]
Sorry this is all I’m seeing — there’s no alfred file, just the source
<img width="596" alt="image" src="https://user-images.githubusercontent.com/2767880/207669865-e6f164b6-fad8-4a85-b82a-3b8cc1c0d759.png">

There’s absolutely no rush on this, just letting you know.

**Comment by fedecalendino** [comment]
It's all right! It seems that the upload failed.

Should be there now.
