### ISSUE TITLE
__pycache__ are included in 2.0.0 release

### ISSUE THREAD

**Issue by vitorgalvao** [fedecalendino/alfred-emoji-mate#7]
I’m guessing that may have been unintentional, since typically that isn’t shared with the distribution.

**Comment by fedecalendino** [comment]
Hi! Thanks for letting me know. Should be fixed in v2.0.1

**Comment by fedecalendino** [comment]
Btw, did you spotted that by eye or do you have a script to validate workflows?

**Comment by vitorgalvao** [comment]
> Btw, did you spotted that by eye or do you have a script to validate workflows?

This could be caught by script alone, but in this case it was a mix of both.

`__pycache__` are still in there, in the `dist` and all the libraries. Python does integrity checks of those so not a huge deal, but mentioned because you didn’t have them before and you seem to care for clean organisation.

**Comment by fedecalendino** [comment]
Thanks, I do care a lot about that haha!

I'll try to figure out later why they keep coming back. :)
